### ISSUE TITLE
UC-03 with Service Workers

### ISSUE THREAD

**Issue by Vermat99** [httpslocal/usecases#9]
I would consider an use case similar to UC-3, but without the frontend page loading from the internet, but locally. This would be possible with Service Workers, that now are under developement also in WebKit. 

With HTTPSlocal and Service Workers would be possible to have a fully working comunication in an offline environment with the browser, requiring the page to be loaded online only once (and maybe refreshed every X days). 

Sorry for my poor knowledge, I just wanted to explain my personal use case and show my support. Thank you.

**Comment by tomoyukilabs** [comment]
@Vermat99 What UC-3 indicates is that the web app provided through HTTPS, i.e. in a [secure context](https://w3c.github.io/webappsec-secure-contexts/), is not allowed to access resources through HTTP because [mixed content](https://w3c.github.io/webappsec-mixed-content/) is restricted in the current web security policy.

Even if the web app is hosted by localhost, it is practically regarded as a secure context and eventually its access to other devices in the same local network through HTTP is blocked due to the mixed content restriction. Such a restriction is also applied to fetch operations by service workers, of course.

Although we could avoid such a restriction by issuing a TLS certificate to each device, the certificate cannot be issued because domain validation (DV) of the device is practically impossible. That is our motivation. If you have an interest, we appreciate your participation. Thanks a lot for your comment!
